### ISSUE TITLE
Spotify crashing immediately after launching app

### ISSUE THREAD

**Issue by Bluemorpho61** [xManager-v2/xManager-Spotify#233]
java.lang.RuntimeException: Unable to instantiate application com.spotify.music.SpotifyApplication: java.lang.ClassNotFoundException: Didn't find class "com.spotify.music.SpotifyApplication" on path: DexPathList[[zip file "/data/app/com.spotify.music-dMTS2L7xsyqELRKR8rAt2A==/base.apk"],nativeLibraryDirectories=[/data/app/com.spotify.music-dMTS2L7xsyqELRKR8rAt2A==/lib/arm64, /data/app/com.spotify.music-dMTS2L7xsyqELRKR8rAt2A==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
	at android.app.LoadedApk.makeApplication(LoadedApk.java:993)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5801)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6651)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.spotify.music.SpotifyApplication" on path: DexPathList[[zip file "/data/app/com.spotify.music-dMTS2L7xsyqELRKR8rAt2A==/base.apk"],nativeLibraryDirectories=[/data/app/com.spotify.music-dMTS2L7xsyqELRKR8rAt2A==/lib/arm64, /data/app/com.spotify.music-dMTS2L7xsyqELRKR8rAt2A==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1088)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:987)
	... 9 more
	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lp/h08;
		at java.lang.VMClassLoader.findLoadedClass(Native Method)
		at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
		... 12 more
	Caused by: java.lang.ClassNotFoundException: Didn't find class "p.h08" on path: DexPathList[[zip file "/data/app/com.spotify.music-dMTS2L7xsyqELRKR8rAt2A==/base.apk"],nativeLibraryDirectories=[/data/app/com.spotify.music-dMTS2L7xsyqELRKR8rAt2A==/lib/arm64, /data/app/com.spotify.music-dMTS2L7xsyqELRKR8rAt2A==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
		... 15 more

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager (Spotify) Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/SpotifyModSupport
